server:
  port: 8082

spring:
  application:
    name: NacosClient
  boot:
    admin:
      client:
        url: http://localhost:8888
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS